name: illusory
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults

dependencies:
  # Core Python
  - python=3.11

  # PyTorch & CUDA
  - pytorch>=2.1.0
#  - pytorch-cuda=12.2  # Installs appropriate CUDA runtime

  # Torch ecosystem
  - torchvision
  - torchaudio

  # Scientific Computing
  - numpy>=1.24.0
  - scipy
  - scikit-learn

  # Image processing
  - pillow>=10.0.0
  - opencv>=4.8.0

  # Web frameworks
  - uvicorn>=0.24.0
  - fastapi>=0.104.0
  - python-multipart>=0.0.6

  # Hugging Face ecosystem
  - transformers>=4.51.0
  - accelerate>=0.25.0
  - tokenizers>=0.15.0
  - huggingface_hub>=0.19.0
  - datasets>=2.14.0
  - hf-xet>=1.0.0

  # Optional: Quantization
  - bitsandbytes>=0.41.0

  # Utilities
  - requests>=2.31.0
  - tqdm>=4.66.0
  - psutil>=5.9.0
  - pydantic>=2.4.0
  - python-dotenv>=1.0.0

  # Development tools
  - git
  - wget
  - curl
